window.GameData = {
  personagens: [
    {
      id: 0,
      img: 'assets/person/mago.png',
      animation: 'assets/sprite/Mago/inicial.gif',
      animationOK: true,
      nome: 'Mago',
      vida: 100,
      mana: 5,
      forca: 5,
      especial: 9,
    },
    {
      id: 1,
      nome: 'Guerreiro',
      img: 'assets/person/guerreiro.png',
      animation: 'assets/sprite/Guerreiro/inicial.gif',
      animationOK: true,
      vida: 120,
      mana: 4,
      forca: 8,
      especial: 5,
    },
    {
      id: 2,
      nome: 'Arqueiro',
      img: 'assets/person/arqueiro.png',
      animation: 'assets/sprite/Arqueiro/inicial.gif',
      animationOK: true,
      vida: 100,
      mana: 5,
      forca: 7,
      especial: 7,
    },
    {
      id: 3,
      nome: 'Ninja',
      img: 'assets/person/ninja.png',
      animation: 'assets/sprite/Ninja/inicial.gif',
      animationOK: true,
      vida: 90,
      mana: 6,
      forca: 9,
      especial: 6,
    },
    {
      id: 5,
      nome: 'Bruxa',
      img: 'assets/person/bruxa.png',
      animation: 'assets/sprite/Bruxa/inicial.gif',
      animationOK: true,
      vida: 90,
      mana: 7,
      forca: 4,
      especial: 11,
    },
  ],
  inimigos: [
    {
      id: 0,
      nome: 'Fera',
      img: 'assets/person/fera.png',
      animation: 'assets/sprite/Fera/inicial.gif',
      animationOK: true,
      vida: 100,
      raiva: 2,
      forca: 10,
    },
    {
      id: 1,
      nome: 'Minotauro',
      img: 'assets/person/minotauro.png',
      animation: 'assets/sprite/Minotauro/inicial.gif',
      animationOK: true,
      vida: 100,
      raiva: 0,
      forca: 12,
    },
    {
      id: 2,
      nome: 'Medusa',
      img: 'assets/person/medusa.png',
      animation: 'assets/sprite/Medusa/inicial.gif',
      animationOK: true,
      vida: 120,
      raiva: 0,
      forca: 10,
    },
    {
      id: 3,
      nome: 'Esqueleto',
      img: 'assets/person/esqueleto.png',
      animation: 'assets/sprite/Esqueleto/inicial.gif',
      animationOK: true,
      vida: 90,
      raiva: 1,
      forca: 9,
    },
    {
      id: 4,
      nome: 'Cavaleiro',
      img: 'assets/person/cavaleiro.png',
      animation: 'assets/sprite/Cavaleiro/inicial.gif',
      animationOK: true,
      vida: 130,
      raiva: 1,
      forca: 11,
    },
  ],
};
