window.GameData = {
  personagens: [
    {
      id: 0,
      img: 'assets/person/mago.jpg',
      animation: 'assets/sprite/Mago/inicial.gif',
      animationOK: true,
      nome: 'Mago',
      vida: 100,
      mana: 5,
      forca: 5,
      especial: 9,
    },
    {
      id: 1,
      nome: 'Guerreiro',
      img: 'assets/person/guerreiro.jpg',
      animation: 'assets/sprite/Guerreiro/inicial.gif',
      animationOK: false,
      vida: 120,
      mana: 4,
      forca: 8,
      especial: 5,
    },
    {
      id: 2,
      nome: 'Arqueiro',
      img: 'assets/person/arqueiro.jpg',
      animation: 'assets/sprite/Arqueiro/inicial.gif',
      animationOK: false,
      vida: 100,
      mana: 5,
      forca: 7,
      especial: 7,
    },
  ],
  inimigos: [
    {
      id: 0,
      nome: 'Fera',
      img: 'assets/person/fera.jpg',
      animation: 'assets/sprite/Fera/inicial.gif',
      animationOK: false,
      vida: 100,
      raiva: 2,
      forca: 10,
    },
    {
      id: 1,
      nome: 'Demônio',
      img: 'assets/person/demonio.jpg',
      animation: 'assets/sprite/Demônio/inicial.gif',
      animationOK: true,
      vida: 100,
      raiva: 0,
      forca: 12,
    },
    {
      id: 2,
      nome: 'Troll',
      img: 'assets/person/troll.jpg',
      animation: 'assets/sprite/Troll/inicial.gif',
      animationOK: false,
      vida: 120,
      raiva: 0,
      forca: 10,
    },
  ],
};
